### ISSUE TITLE
Reduce repetition of "services" block in GitHub Actions test.yml

### ISSUE THREAD

**Issue by cmgriffing** [Vexilla/vexilla#11]
Each job in the test.yml file has this block:

```yaml
    services:
      test-server:
        credentials:
          username: vexilla
          password: ${{secrets.GITHUB_TOKEN}}
        image: ghcr.io/vexilla/test-server:latest
        ports:
          - 3000:3000
        options: |
          --health-cmd "curl -f http://localhost:3000/manifest.json"
```

It would be nice to only have to define it once. An initial attempt tried to define a top level services value, but that didn;t seem to be correct for the schema that GitHub expects.

Is there some way to reduce the repetition of that block being in multiple places?
